### ISSUE TITLE
ratted dont use

### ISSUE THREAD

**Issue by qoft** [dev-vince/minecraft-deobfuscated#5]
Minecraft.java is ratted!

**Comment by dev-vince** [comment]
nuh uh

**Comment by qoft** [comment]
uh huh

**Comment by dev-vince** [comment]
rat = false;

**Comment by qoft** [comment]
private final boolean rat = false;

ur bad at coding vince

**Comment by dev-vince** [comment]
no ur actually worse at coding than me

private final boolean rat = true;

rat = null;

**Comment by qoft** [comment]
mexican jew
![vince](https://user-images.githubusercontent.com/63415260/202738126-d8d4c791-8051-43cb-a2bd-5c822670428a.png)

**Comment by dev-vince** [comment]
😔
